services:
    postgres:
        image: postgres:17-alpine
        environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=root
        ports:
            - "5432:5432"
        healthcheck:
            test: pg_isready
            interval: 10s
            timeout: 5s
            retries: 5
